### ISSUE TITLE
Save and open projects

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#16]
It should be possible to save and open a project to share them or simply resume working on them.

Maybe `.workbench`

Would be awesome to support versioning (ie save the last X versions of the files) for undo

**Comment by sonnyp** [comment]
Added support for save on change but not projects - deprio

**Comment by karl0d** [comment]
Hey, I'm big fan of your application and I'd like to help with this issue, because the lack of project config  makes it hard to use it for me (and presumably for lots of people). 

My idea is to import project files from toml/yaml config that instead of importing each file separately. I hope I don't have to explain to you how bad and annoying it is.

It would be also really cool to some some kind of tree view, but I'm not sure if that's in like with project goals.

**Comment by karl0d** [comment]
An example toml config would like like that:
```toml
authors = ["Me"]
name = "Design Playground"

[project]
	source = "widget.js"
	stylesheet = "style.css"
	template = "widget.ui"

[[subprojects]]
	authors = ["Me", "My cat"]
	name = "MyCoolWidget"
	path = "my_cool_widget" #or path = "./my_cool_widget"
	source = "cool_widget.rs"
	stylesheet = "index.css"
	template = "cool-widget.blp"
```
