### ISSUE TITLE
Dropdown library entry

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#268]
# Description

We should have a dropdown demo with custom GListModel and expression

Here is a simpple dropdown example

```css
      DropDown dropdown_langs {
        enable-search: true;
        model: StringList {
          strings ["GNOME", "Linux", "mobile", "GTK", "GJS"]
        };
      }
```

```js
  const expression = new Gtk.ClosureExpression(
    GObject.TYPE_STRING,
    (obj) => obj.string,
    null,
  );
  dropdown_langs.expression = expression;
```

# Bookmarks

* https://developer.gnome.org/hig/patterns/controls/drop-downs.html
* https://docs.gtk.org/gtk4/class.DropDown.html
