### ISSUE TITLE
Drop Zone entry

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#368]
We should have a demo that demonstrates how to have a drop zone which can be used to drop a file or text or anything from outside the app.

I would suggest making something like this to start with

EDIT: nevermind this design refer to the commet below

![image](https://github.com/sonnyp/Workbench/assets/19673/6ef70ccc-162d-4ee1-bb6e-f8ec58ace7a1)

The zone should highlight or animate when there is a drag over it. 
In GNOME we usually show an inset border of 1px.  See for example with https://apps.gnome.org/app/app.drey.Warp/
There is also a good example here: https://www.dropzone.dev/

Code:

```blp
using Gtk 4.0;
using Adw 1;

Adw.StatusPage {
  title: "Drop Zone";
  description: "Accept data dragged from other applications";
  Box {
    margin-top: 48;
    hexpand: true;
    vexpand: true;
    halign: center;
    valign: center;
    orientation: vertical;

    Box {
      name: "drop";
      width-request: 200;
      height-request: 200;
      Label {
        name: "label";
        label: _("<b>Drop</b>");
        use-markup: true;
        hexpand: true;
      }
    }
  }
}

```

```css
#drop {
  border: dashed 6px @dark_3;
  border-radius: 25%;
  background-color: white;
  
}

#label {
  color: @dark_3;
}
```
